<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="qbit.MppTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2019-11-03T12:18:44" hostname="atomic-armchair" time="0.005">
  <properties/>
  <testcase name="test" classname="qbit.MppTest" time="0.005">
    <failure message="kotlin.AssertionError: Expected value to be true.&#10;        at kfun:kotlin.Error.&lt;init&gt;(kotlin.String?)kotlin.Error (0x277e75)&#10;        at kfun:kotlin.AssertionError.&lt;init&gt;(kotlin.Any?)kotlin.AssertionError (0x278564)&#10;        at kfun:kotlin.test.DefaultAsserter.fail(kotlin.String?)kotlin.Nothing (0x2657f4)&#10;        at kfun:kotlin.test.Asserter.assertTrue(kotlin.Function0&lt;kotlin.String?&gt;;kotlin.Boolean) (0x262688)&#10;        at kfun:kotlin.test.Asserter.assertTrue(kotlin.String?;kotlin.Boolean) (0x2627f9)&#10;        at kfun:kotlin.test.assertTrue(kotlin.Boolean;kotlin.String?) (0x265416)&#10;        at kfun:kotlin.test.assertTrue$default(kotlin.Boolean;kotlin.String?;kotlin.Int) (0x26554d)&#10;        at kfun:qbit.MppTest.test() (0x3485d0)&#10;        at kfun:qbit.$MppTest$test$0.$test$FUNCTION_REFERENCE$0.invoke#internal (0x348883)&#10;        at kfun:qbit.$MppTest$test$0.$test$FUNCTION_REFERENCE$0.$&lt;bridge-UNNN&gt;invoke(#GENERIC)#internal (0x3488f9)&#10;        at kfun:kotlin.native.internal.test.BaseClassSuite.TestCase.run() (0x2bb80c)&#10;        at kfun:kotlin.native.internal.test.TestRunner.run#internal (0x2b57ad)&#10;        at kfun:kotlin.native.internal.test.TestRunner.runIteration#internal (0x2b696b)&#10;        at kfun:kotlin.native.internal.test.TestRunner.run()ValueType (0x2b7291)&#10;        at kfun:kotlin.native.internal.test.testLauncherEntryPoint(kotlin.Array&lt;kotlin.String&gt;)ValueType (0x2aafa1)&#10;        at kfun:kotlin.native.internal.test.main(kotlin.Array&lt;kotlin.String&gt;) (0x2aae77)&#10;        at Konan_start (0x272adb)&#10;        at Init_and_run_start (0x34dfab)&#10;        at __libc_start_main (0x7f26c6295153)&#10;        at  (0x24e029)&#10;        at  ((nil))&#10;" type="kotlin.AssertionError">kotlin.AssertionError: Expected value to be true.
        at kfun:kotlin.Error.&lt;init&gt;(kotlin.String?)kotlin.Error (0x277e75)
        at kfun:kotlin.AssertionError.&lt;init&gt;(kotlin.Any?)kotlin.AssertionError (0x278564)
        at kfun:kotlin.test.DefaultAsserter.fail(kotlin.String?)kotlin.Nothing (0x2657f4)
        at kfun:kotlin.test.Asserter.assertTrue(kotlin.Function0&lt;kotlin.String?&gt;;kotlin.Boolean) (0x262688)
        at kfun:kotlin.test.Asserter.assertTrue(kotlin.String?;kotlin.Boolean) (0x2627f9)
        at kfun:kotlin.test.assertTrue(kotlin.Boolean;kotlin.String?) (0x265416)
        at kfun:kotlin.test.assertTrue$default(kotlin.Boolean;kotlin.String?;kotlin.Int) (0x26554d)
        at kfun:qbit.MppTest.test() (0x3485d0)
        at kfun:qbit.$MppTest$test$0.$test$FUNCTION_REFERENCE$0.invoke#internal (0x348883)
        at kfun:qbit.$MppTest$test$0.$test$FUNCTION_REFERENCE$0.$&lt;bridge-UNNN&gt;invoke(#GENERIC)#internal (0x3488f9)
        at kfun:kotlin.native.internal.test.BaseClassSuite.TestCase.run() (0x2bb80c)
        at kfun:kotlin.native.internal.test.TestRunner.run#internal (0x2b57ad)
        at kfun:kotlin.native.internal.test.TestRunner.runIteration#internal (0x2b696b)
        at kfun:kotlin.native.internal.test.TestRunner.run()ValueType (0x2b7291)
        at kfun:kotlin.native.internal.test.testLauncherEntryPoint(kotlin.Array&lt;kotlin.String&gt;)ValueType (0x2aafa1)
        at kfun:kotlin.native.internal.test.main(kotlin.Array&lt;kotlin.String&gt;) (0x2aae77)
        at Konan_start (0x272adb)
        at Init_and_run_start (0x34dfab)
        at __libc_start_main (0x7f26c6295153)
        at  (0x24e029)
        at  ((nil))

</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
